stages:
  preprocess:
    cmd: python -m src.data.make_dataset data/raw/train.csv data/processed/train.pkl
    deps:
    - data/raw/train.csv
    outs:
    - data/processed/train.pkl

  train:
    cmd: python -m src.models.train_models data/processed/train.pkl models
    deps:
    - data/processed/train.pkl
    outs:
    - models/catboost_native.pkl
    - models/catboost_tr.pkl

  test:
    cmd: python -m src.models.test_models models data/processed/train.pkl metrics/test
    deps:
    - models/catboost_native.pkl
    - models/catboost_tr.pkl
    metrics:
    - metrics/test/catboost_native.json
    - metrics/test/catboost_tr.json