stages:
  preprocess_train:
    cmd: python -m src.data.make_dataset data/raw/train.csv data/processed/train.pkl
    deps:
    - src/data/make_dataset.py
    - src/data/preprocess.py
    - data/raw/train.csv
    outs:
    - data/processed/train.pkl

  preprocess_test:
    cmd: python -m src.data.make_dataset data/raw/test.csv data/processed/test.pkl --input_answers=data/raw/sample_submission.csv
    deps:
    - src/data/make_dataset.py
    - src/data/preprocess.py
    - data/raw/test.csv
    - data/raw/sample_submission.csv
    outs:
    - data/processed/test.pkl

  train:
    cmd: python -m src.models.run_train data/processed/train.pkl models
    deps:
    - src/models/common.py
    - src/models/run_train.py
    - src/features/feature_transformer.py
    - src/models/catboost_models.py
    - src/models/sklearn_models.py
    - data/processed/train.pkl
    outs:
    - models/catboost_native.pkl
    - models/catboost_tr.pkl
    - models/extra_trees.pkl

  predict_test:
    cmd: python -m src.models.run_predict models data/processed/train.pkl predictions/test
    deps:
    - src/models/common.py
    - src/models/run_predict.py
    - models/catboost_native.pkl
    - models/catboost_tr.pkl
    - models/extra_trees.pkl
    outs:
    - predictions/test/catboost_native.json
    - predictions/test/catboost_tr.json
    - predictions/test/extra_trees.json
  
  score_test:
    cmd: python -m src.models.run_score predictions/test data/processed/train.pkl metrics/test
    deps:
    - src/models/common.py
    - src/models/run_score.py
    - predictions/test/catboost_native.json
    - predictions/test/catboost_tr.json
    - predictions/test/extra_trees.json
    metrics:
    - metrics/test/catboost_native.json
    - metrics/test/catboost_tr.json
    - metrics/test/extra_trees.json

  predict_validate:
    cmd: python -m src.models.run_predict models data/processed/test.pkl predictions/validate --split=False
    deps:
    - src/models/common.py
    - src/models/run_predict.py
    - models/catboost_native.pkl
    - models/catboost_tr.pkl
    - models/extra_trees.pkl
    outs:
    - predictions/validate/catboost_native.json
    - predictions/validate/catboost_tr.json
    - predictions/validate/extra_trees.json
  
  score_validate:
    cmd: python -m src.models.run_score predictions/validate data/processed/test.pkl metrics/validate --split=False
    deps:
    - src/models/common.py
    - src/models/run_score.py
    - predictions/validate/catboost_native.json
    - predictions/validate/catboost_tr.json
    - predictions/validate/extra_trees.json
    metrics:
    - metrics/validate/catboost_native.json
    - metrics/validate/catboost_tr.json
    - metrics/validate/extra_trees.json